---
title: "Traffic in Bolzano"
output: 
  flexdashboard::flex_dashboard:
    social: menu
    theme: yeti
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
# Libraries for data manipulation and visualization
library("shinythemes")
library("flexdashboard")
library("DBI")
library("dplyr")
library("ggplot2")
library("tidyverse")
library("shinyWidgets")
library("shiny")
library("plotly")
library("scales")
library("DT")
library("leaflet")
library("leaflet.extras")
library("maps")
library("rio")

# Connection to DB
source("mysql_connection.R")
library("RMariaDB")

# Establish connectiong to MySQL
con <- mysqldbconnect()
mongo_db <- mongodbconnect()

# Inserting token of mapbox for styling
mapboxToken <- config::get(file = "config.yml")$mapbox
Sys.setenv("MAPBOX_TOKEN" = mapboxToken)
```


Real time traffic
=====================================  
```{r}
# Input for selecting a map style
selectInput(inputId = "map_style", 
            label = "Select a style",
            choices = c("streets","open-street-map","light","dark"))
            #width = "100%")

# Palettes for real-time map
palettes = list("streets" = pals::kovesi.diverging_rainbow_bgymr_45_85_c67(5),
                 "open-street-map" = pals::kovesi.linear_bmy_10_95_c78(5),
                 "light" = pals::brewer.ylorrd(10),
                 "dark" = pals::plasma(50))
```

### Traffic prediction

```{r}
renderPlotly({
  
  latest_timestamp = mongo_db$find(sort = '{"timestamp":-1}', limit=1)$timestamp[1]
  latest_data = mongo_db$find(paste0('{"timestamp":"',latest_timestamp,'"}')) %>%
    inner_join(dbGetQuery(con, paste0(
      "SELECT * FROM bluetoothstations.station 
       WHERE latitude IS NOT NULL and longitude IS NOT NULL;"
    )),by = c("station"="name"))
  
  # Plotting
  map_style = input$map_style[1]
  plot_mapbox(df) %>%
  add_markers(
    x = ~longitude, 
    y = ~latitude, 
    size = ~count, 
    color = ~count,
    colors = palettes[map_style][[1]],
    # on hover information
    text = ~paste(station,
                  '</br></br>Vehicles: ', count),
    hoverinfo = "text",
    marker=list(opacity = 1,
                size = seq(200,500))
  )%>%
    layout(
      mapbox = list(
        style = map_style, # setting the style
        zoom = 12.5,         
        center = list(lon = 11.35, lat = 46.485)), # centering on Bolzano
      margin = list(l = 0, r = 0, # No Margin around the plot
                    b = 0, t = 0,
                    pad = 0))
})%>%
bindCache(input$map_style)
```


Stations {data-orientation=columns}
=====================================   

```{r}
# List of stations' names
stations = c(dbGetQuery(con, paste0(
      "SELECT name
       FROM bluetoothstations.station"
    )))

# Search bar for the stations
selectInput(inputId = "station", 
            label = "Select a station",
            choices = c("All",stations),
            width = "50%")
```

Column {data-width=400}
-------------------------------------
    
### Stations

```{r}
# Creating the map that shows the selected station
renderPlotly({
  
  # Show all stations
  if(input$station[1]!="All"){
    df = dbGetQuery(con, paste0(
      "SELECT *
       FROM bluetoothstations.station
       WHERE name ='",input$station[1],"'"
    ))
    
  # Show the selected station
  }else{
    df = dbGetQuery(con, paste0(
      "SELECT *
       FROM bluetoothstations.station;"))
  }
  
  plot_mapbox(df) %>%
  add_markers(
    x = ~longitude, 
    y = ~latitude,
    text = ~name,
    hoverinfo = "text",
    marker=list(opacity = 1,
                size = 10,
                color= '#98d499'))%>%
    layout(
      mapbox = list(
        style = 'light',
        zoom = 8.5,
        center = list(lon = 11.25, lat = 46.35)),
      margin = list(l = 0, r = 0,
                    b = 0, t = 0,
                    pad = 0))
})%>%
bindCache(input$station)
```
   
Column {data-width=600}
-------------------------------------
   
### Traffic per hour

```{r}
renderPlotly({
  
  # Query: traffic of the specific station
  if(input$station[1]!="All"){
    traffic_s = dbGetQuery(con,paste0("
    SELECT *
    FROM bluetoothstations.station_traffic_per_hour
    WHERE station = '",input$station[1],"';"))

  # Query: traffic of the overall stations
  }else{
    traffic_s = dbGetQuery(con,paste0("SELECT hour, AVG(mean) as mean
                                      FROM bluetoothstations.station_traffic_per_hour
                                      GROUP BY hour;"))
  }
  
  # Plotting data inside queries
  plot_ly(traffic_s,
          x = ~hour,
          y = ~mean, 
          type = 'bar',
          text = ~paste(hour,
                  '</br></br>Average no. of vehicles: ', mean),
          hoverinfo = 'text',
          color = ~mean,
          colors = pals::kovesi.isoluminant_cgo_80_c38(24)
          ) %>%
    layout(
      xaxis = list(title = 'Hour'),
      yaxis = list(title = 'Average traffic')
    )
})%>%
  bindCache(input$station)
```

### Traffic over the day

```{r}
renderPlotly({
  if(input$station[1]!="All"){
    traffic_s = dbGetQuery(con,paste0("
    SELECT hour, mean
    FROM bluetoothstations.station_traffic_per_hour
    WHERE station = '",input$station[1],"';"))
    title_p = paste0("Average traffic per hour of station ",input$station[1])
    
  # Plot the traffic of the overall stations
  }else{
    traffic_s = dbGetQuery(con,paste0("
                                      SELECT hour, AVG(mean) as mean
                                      FROM bluetoothstations.station_traffic_per_hour
                                      GROUP BY hour;"))
    title_p = "Average traffic per hour"
  }
  traffic_s <-traffic_s %>%
    mutate(daytime = ifelse(hour>=6 & hour<12,"Morning",
                            ifelse(hour>=12 & hour<18,"Afternoon",
                                   ifelse(hour>=18,"Evening",
                                          "Night"))))
  traffic_s_sum = traffic_s %>%
    select(daytime,mean) %>%
    rename(hour = daytime) %>%
    group_by(hour) %>%
    summarise(mean = mean(mean)) %>%
    mutate(daytime = "")
  rbind(traffic_s,
        traffic_s_sum) %>%
  plot_ly(type='treemap',
          labels = ~hour,
          parents = ~daytime,
          values = ~mean,
          hoverinfo = ~mean) %>%
    layout(treemapcolorway=c("#d0f4de","#fcf6bd","#a9def9","#e4c1f9"))
})
```


History
=====================================    

```{r}
latest_data = dbGetQuery(con,"SELECT DATE(MAX(timestamp))
                         FROM bluetoothstations.measurement;")

# Date range input
dateRangeInput(inputId = "pickup_date", 
  label = 'Date range: ', 
  start = format(latest_data-5,'%Y-%m-%d')[[1]], 
  end = format(latest_data,'%Y-%m-%d')[[1]], 
  min = "2013-01-01",
  max = format(latest_data,'%Y-%m-%d')[[1]],
  startview = "year")

textOutput("Please, select a timerange larger than 5 days.")

```

Column {data-width=600}
-------------------------------------

### Historical trend of traffic

```{r}
# === HANDLE EXCEPTIONS:
# === 1. start >= end
# === 2. distance between start and end < 5 days

renderPlotly({
  start = input$pickup_date[1]
  end = input$pickup_date[2]
  if(start >= end){
   start = format(latest_data-5,'%Y-%m-%d')[[1]]
   end = format(latest_data,'%Y-%m-%d')[[1]]
  }
  history = dbGetQuery(con,paste0("
    SELECT timestamp, SUM(count) as vehicles
    FROM bluetoothstations.measurement
    WHERE timestamp BETWEEN '",input$pickup_date[1],"' AND '",input$pickup_date[2],"' 
    GROUP BY timestamp;"))
  ggplotly(ggplot(data = history,
                  aes(x=timestamp,
                      y = vehicles,
                      text = paste("Date: ",format(timestamp,"%Y-%m"))))+
             geom_smooth(fill='#BFDCED',
                         span = 0)+
             labs(title = paste0("Traffic from ",input$pickup_date[1]," to ",input$pickup_date[2]))+
             theme_classic()+
             theme(plot.title = element_text(hjust = 0.5)),tooltip=c('text','vehicles'))
})
```

Column {data-width=400}
-------------------------------------

### Dates with most or least traffic

```{r}
renderDataTable({
  history = dbGetQuery(con,paste0("
    SELECT timestamp, SUM(count) as vehicles
    FROM bluetoothstations.measurement
    WHERE timestamp BETWEEN '",input$pickup_date[1],"' AND '",input$pickup_date[2],"' 
    GROUP BY timestamp;")) 
  history$timestamp = format(history$timestamp, "%Y-%m-%d %H:%M")
  datatable(history,
            options = list(pageLength = 20,
               lengthMenu = list(c(10, 20, -1), c('10', '20', 'All')),
               order = list(list(2, 'desc'))))
})
```


Timing trends 
=====================================    

Column {data-width=600}
-------------------------------------

### Traffic for weekdays
```{r}
renderPlotly({
  palette = c("#ffadad","#ffd6a5","#e6f68e","#caffbf","#9bf6ff","#a0c4ff","#ffc6ff")
  data = dbGetQuery(con,paste0("
                               SELECT weekday, hour, AVG(mean) as mean
                               FROM bluetoothstations.time_group
                               GROUP BY weekday, hour;"))
  data$weekday = factor(data$weekday,order=TRUE,levels = c('Sunday','Saturday','Friday','Thursday','Wednesday','Tuesday','Monday'))
  plot_ly(data = data, x = ~hour,colors = palette) %>%
    add_lines(y = ~mean,color = ~weekday)
})
```

### Traffic for months

```{r}
assign_daytime = function(hour){
  ifelse(hour>=6 & hour<12,"Morning",
         ifelse(hour>=12 & hour<18,"Afternoon",
                ifelse(hour>=18,"Evening",
                       "Night")))
}

renderPlotly({
  data = dbGetQuery(con,paste0("SELECT month, hour, AVG(mean) as vehicles
                               FROM bluetoothstations.time_group
                               GROUP BY hour, month
                               ORDER BY hour;"))
    # Mapping months to string
  months = c("January","February","March",
             "April","May","June",
             "July","August","September",
             "October","November","December")
  data$month = months[as.integer(data$month)]
  data$month = factor(data$month, order = TRUE, levels = months)
  data$hour = factor(assign_daytime(data$hour), order = TRUE,levels = c("Night","Evening","Afternoon","Morning"))
  data %>%
    group_by(month,hour) %>%
    summarise(vehicles = mean(vehicles)) %>%
    arrange(month,hour)%>%
  plot_ly(colors = c('#FFADD3','#a9def9','#FBF4B1','#CDF3DC'),
          x = ~month,
          y = ~vehicles,
          color = ~hour,
          type='bar')%>%
    layout(barmode = 'group')
})
```

Column {data-width=400}
-------------------------------------

### Traffic over weekdays and time of the day

```{r}
renderPlotly({
  data = dbGetQuery(con,"SELECT weekday, hour, AVG(sum) as vehicles
                               FROM bluetoothstations.time_group
                               GROUP BY weekday, hour;")
  data_second = data %>%
    group_by(weekday) %>%
    summarise(count = sum(vehicles)) %>%
    rename(hour = weekday) %>%
    mutate(weekday = '')
  data$hour = assign_daytime(data$hour)
  data %>%
    group_by(weekday,hour) %>%
    summarise(count = sum(vehicles)) %>%
    rbind(data_second) %>%
    mutate(ids = paste0(weekday,hour)) %>%
  plot_ly() %>%
    add_trace(
      type = 'sunburst',
      ids = ~ids,
      labels = ~hour,
      parents = ~weekday, 
      values = ~count,
      branchvalues = 'total'
    ) %>%
    layout(sunburstcolorway = c("#ffadad","#ffd6a5","#FBF4B1","#CDF3DC","#a9def9","#bbadff","#FFADD3"))
})
```


### Traffic over different seasons

```{r}
renderPlotly({
  
  # Query with data about months
  data = dbGetQuery(con,"SELECT month, AVG(sum) as vehicles
                               FROM bluetoothstations.time_group
                               GROUP BY month;")
  # Column with seasons
  data$season = ifelse(data$month %in% c(12,1,2),'Winter',
                       ifelse(data$month %in% c(3,4,5), 'Spring',
                              ifelse(data$month %in% c(6,7,8), 'Summer','Autumn')))
  # Mapping months to string
  months = c("January","February","March",
             "April","May","June",
             "July","August","September",
             "October","November","December")
  data$month = months[as.integer(data$month)]
  data %>%
    group_by(season) %>%
    summarise(vehicles = sum(vehicles))%>%
    rename(month = season) %>%
    mutate(season = "") %>%
    rbind(data) %>%
  # Plot the sunburst
  plot_ly(labels = ~month,
          parents = ~season, 
          type = 'sunburst',
          values = ~vehicles,
          branchvalues = 'total') %>%
    layout(sunburstcolorway = c('#FFADD3','#a9def9','#FBF4B1','#CDF3DC'))
})
```

